export const projects = [
  {
    id: 'llm-integration',
    title: 'LLM Integration for Game Engines',
    description: 'Architected AI-powered training system for government project, securing $2M in follow-on funding. Built production infrastructure and designed plugin architecture for seamless integration.',
    tech: ['Unity', 'Python', 'Kubernetes', 'Langchain', 'Microservices'],
    highlight: '$2M Funding Secured',
    image: '/projects/llm-integration.png',
  },
  {
    id: 'training-maturation',
    title: 'Training Platform Maturation',
    description: 'Leading technical modernization of Unity training system after gap analysis secured contract award. Architecting improvements to ensure stability, performance, and maintainability.',
    tech: ['Unity', 'Requirements Definition', 'System Architecture', 'DevOps'],
    highlight: 'Contract Award',
    // image: '/projects/unity-training.jpg',
  },
  {
    id: 'baseball-training',
    title: 'Deterministic Baseball Simulation',
    description: 'Led development of mobile training application using Unity DOTS, integrating computer vision pose estimation with deterministic physics for frame-perfect replay and analysis.',
    tech: ['Unity', 'DOTS', 'iOS', 'Cocoapods', 'Computer Vision'],
    highlight: 'Technical Lead',
    // image: '/projects/baseball.jpg',
  },
  {
    id: 'crewed-uncrewed',
    title: 'Uncrewed Command & Control Interface',
    description: 'Designed networked tactical interface for uncrewed operations using Unreal Engine 5 on dual iPads. Implemented custom RPCs and Protobuf messaging with <50ms latency for mission-critical operations.',
    tech: ['Unreal Engine 5', 'iOS', 'Protobuf', 'Networking', 'Cesium'],
    highlight: 'Advanced Visualization',
    // image: '/projects/military-interface.jpg',
  },
  {
    id: 'nfl-vr',
    title: 'VR Football Demo Management',
    description: 'Built demo orchestration system for NFL Pro Era, enabling real-time control of 20+ scenarios. Created CloudXR streaming client for wireless Meta Quest demos at conventions.',
    tech: ['Unity', 'Meta Quest', 'CloudXR', 'OSC', 'JNI'],
    highlight: 'Cool Tools',
    image: '/projects/nfl-vr.jpg',
  },
  {
    id: 'xr-cockpit',
    title: 'XR Pilot Vehicle Interface',
    description: 'Developed experimental mixed reality cockpit interface for aviation applications using Unreal Engine 4. Created 3D spatial UI with gesture controls through 12+ design iterations.',
    tech: ['Unreal Engine 4', 'XR', 'Vive Pro', 'C++'],
    highlight: 'Rapid Prototyping',
    // image: '/projects/xr-cockpit.jpg',
  },
]